Session/8
macneko-ayu/yumemi-flutter-training pull request #21
Opened 2024-06-05 07:04 UTC by macneko-ayu

## 課題

close #9 

## 対応箇所

- [x] [Riverpod] を導入して、天気予報画面の状態管理を見直す
- [x] アーキテクチャを見直し、ARCHITECTURE.md に記載する

## 動作

動作に変更なしです

2024-06-05 07:07 UTC, macneko-ayu commented on analysis_options.yaml
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)
[公式ドキュメント](https://riverpod.dev/docs/introduction/getting_started#enabling-riverpod_lintcustom_lint)に倣って追加しました

2024-06-05 07:08 UTC, macneko-ayu commented on build.yaml
> +            '^lib/{{dir}}/{{file}}.dart': 'lib/{{dir}}/generated/{{file}}.g.dart'
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)
`data` 配下以外も自動生成の対象にしたかったので、汎用的なファイル指定に修正しました

2024-06-05 07:09 UTC, macneko-ayu commented on build.yaml
> +            - duplicate_ignore
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)
重複したときにワーニングが出力されないように追加しました

2024-06-05 07:11 UTC, macneko-ayu commented on lib/data/generated/weather.g.dart
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)
[build.yaml](https://github.com/macneko-ayu/yumemi-flutter-training/pull/21/files#diff-2f7f69286606c0ff1642fac8ecb40ee91874b65bb544af172e32552c91a44799R10) 修正の影響ですが、実装内容に変更はないです

2024-06-05 07:11 UTC, macneko-ayu commented on lib/data/generated/weather_request.g.dart
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)
[build.yaml](https://github.com/macneko-ayu/yumemi-flutter-training/pull/21/files#diff-2f7f69286606c0ff1642fac8ecb40ee91874b65bb544af172e32552c91a44799R10) 修正の影響ですが、実装内容に変更はないです

2024-06-05 07:13 UTC, macneko-ayu commented on lib/presentation/screen/weather/weather_screen.dart
> +class WeatherNotifier extends _$WeatherNotifier {
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)
Screen の State を新たに用意して、その State を管理する Notifier を作成するかちょっと考えたんですが、規模に対して過剰だと思って、シンプルな Notifier にしました

2024-06-05 07:15 UTC, macneko-ayu commented on lib/presentation/screen/weather/weather_screen.dart
> +class WeatherNotifier extends _$WeatherNotifier {
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)
Notifier の定義場所に悩んで Screen を司るファイルに実装したのですが、別ファイルにしたほうがよいでしょうか

2024-06-05 07:16 UTC, macneko-ayu commented on lib/presentation/screen/weather/weather_screen.dart
> +                      closeTapped: () => Navigator.of(context).pop(),
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)
前のセッションで対応が漏れていたので、close ボタンタップ時も Callback に書き換えました

2024-06-05 07:19 UTC, macneko-ayu commented
@blendthink 遅くなってすみません、レビューお願いします！

2024-06-05 09:41 UTC, macneko-ayu commented on lib/repository/weather_repository.dart
>    final _client = YumemiWeather();
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)
次のSessionでDIするように修正します

2024-06-05 09:42 UTC, macneko-ayu commented on lib/repository/weather_repository.dart
>    final _client = YumemiWeather();
あわせて使っていないメソッドも削除します

2024-06-06 02:14 UTC, macneko-ayu commented on lib/repository/weather_repository.dart
>    final _client = YumemiWeather();
一晩考えて、このPRで対応することにしました🙏

2024-06-06 03:04 UTC, macneko-ayu commented on lib/repository/weather_repository.dart
>    final _client = YumemiWeather();
不要な処理の削除を以下のコミットで行いました
e8ee7f3d200ec5481ab8ce2f93e3f6ce35ab6da5
919713399508163c519b9c5f4613d3e893567957
de955081a6caeba34aceebb84971cad560b01974

2024-06-06 03:04 UTC, macneko-ayu commented on lib/repository/weather_repository.dart
>    final _client = YumemiWeather();
DIは aaa692471e6053917ab830364537bbf0708c235d で修正しました

2024-06-06 03:05 UTC, macneko-ayu commented on analysis_options.yaml
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)
[公式ドキュメント](https://riverpod.dev/docs/introduction/getting_started#enabling-riverpod_lintcustom_lint)に倣って追加しました

2024-06-06 03:17 UTC, macneko-ayu commented
修正が終わったので、Draft解除しました

2024-06-06 10:49 UTC, macneko-ayu commented on lib/data/generated/weather.g.dart
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)
build.yaml 修正の影響ですが、実装内容に変更はないです

2024-06-06 10:49 UTC, macneko-ayu commented on lib/data/generated/weather_request.g.dart
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)
build.yaml 修正の影響ですが、実装内容に変更はないです

2024-06-06 10:50 UTC, macneko-ayu commented on lib/data/weather_condition.dart
> -  factory WeatherCondition.from(String name) {
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)
現状利用していないので削除しました

2024-06-06 10:51 UTC, macneko-ayu commented on lib/repository/weather_repository.dart
> -  WeatherCondition? fetchSimpleWeather() {
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)
現状利用していないので削除しました

2024-06-06 10:51 UTC, macneko-ayu commented on lib/repository/weather_repository.dart
> -  WeatherCondition? fetchThrowsWeather(String area) {
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)
現状利用していないので削除しました

2024-06-06 10:52 UTC, macneko-ayu commented on lib/repository/weather_repository.dart
> +  const WeatherRepository({required YumemiWeather client}) : _client = client;
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)
Session9でリファクタリングしようと思ったのですが、Riverpod導入時にやっておくことにしました

2024-06-06 10:53 UTC, macneko-ayu commented
気になったところの修正が終わったのでレビューお願いします🙏

2024-06-12 07:56 UTC, blendthink requested changes
@macneko-ayu 
いくつかコメントさせていただきましたのでご確認お願いします 🙏

2024-06-12 07:56 UTC, blendthink commented on ARCHITECTURE.md
> +- freezed, riverpod を利用して、可能な限り immutable にする
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg)
基本方針記載されていて、とてもステキです✨

2024-06-12 07:56 UTC, blendthink commented on ARCHITECTURE.md
> +    - `common` : 複数画面から利用されるクラスyが格納される
![nits-badge](https://img.shields.io/badge/review-nits-orange.svg)
typo 発見しました 💡

2024-06-12 07:56 UTC, blendthink commented on ARCHITECTURE.md
> +```
![nits-badge](https://img.shields.io/badge/review-nits-orange.svg)
NotifierProvider　が RepositoryProvider を read しているところが欠けてしまっているかもです。

2024-06-12 07:56 UTC, blendthink commented on ARCHITECTURE.md
> +## ディレクトリ構造
![imo-badge](https://img.shields.io/badge/review-imo-skyblue.svg) 
infra ディレクトリも記載していたほうが丁寧で良さそうに思いました。

2024-06-12 07:56 UTC, blendthink commented on lib/presentation/screen/weather/weather_screen.dart
> +      unawaited(_showErrorDialog(context, e.message));
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg)
不要な await 処理の修正ありがとうございます！

2024-06-12 07:56 UTC, blendthink commented on lib/presentation/screen/weather/weather_screen.dart
> -    }
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)
引き続き `mounted` の判定はしておいたほうが良いかなと思ったのですが、何かこのようにした理由があれば教えてください 🙏 
特になければ `context.mounted` が利用できるので、それで処理していただければと思います。

2024-06-12 07:56 UTC, blendthink commented on lib/repository/weather_repository.dart
> +  final client = ref.read(yumemiWeatherProvider);
![must-badge](https://img.shields.io/badge/review-must-red.svg)
想定外の不具合を予防するためにも Provider 内では `ref.watch` を使用するようにお願いします。
```suggestion
  final client = ref.watch(yumemiWeatherProvider);
```

2024-06-20 09:36 UTC, macneko-ayu commented on ARCHITECTURE.md
> +    - `common` : 複数画面から利用されるクラスyが格納される
お恥ずかしい… 😇 
03574712d45906b8891adc30989a433671e66dc3 で修正しました

2024-06-20 09:36 UTC, macneko-ayu commented on ARCHITECTURE.md
> +```
90264574b7778967abb7c6306aa9a2cc98566145 で修正しました

2024-06-20 09:36 UTC, macneko-ayu commented on ARCHITECTURE.md
> +## ディレクトリ構造
f8544722efc7ce5a1baa998bd86aa968072f278a で修正しました

2024-06-20 09:37 UTC, macneko-ayu commented on lib/presentation/screen/weather/weather_screen.dart
> -    }
間違えました！！！
4caae2b2a1ae90942d0a1dc7d24b0b5266d33090 で修正しました

2024-06-20 09:37 UTC, macneko-ayu commented on lib/repository/weather_repository.dart
> +  final client = ref.read(yumemiWeatherProvider);
94e6233a1773357cd1ea45a72b2be70a3f0cbe01 で修正しました

2024-06-20 09:38 UTC, macneko-ayu commented
@blendthink 
修正が遅くなってすみません。再度レビューお願いします！

2024-06-20 09:39 UTC, blendthink approved these changes
ご対応ありがとうございました！

![LGTM](https://image.lgtmoon.dev/75651)

2024-06-20 09:49 UTC, merged