Session/10
macneko-ayu/yumemi-flutter-training pull request #23
Opened 2024-06-27 09:14 UTC by macneko-ayu

## 課題

close #11

## 対応箇所

- [x] 次の Widget tests を書く
    - [x] 特定の条件で、天気予報画面に晴れの画像が表示されること
    - [x] 特定の条件で、天気予報画面に曇りの画像が表示されること
    - [x] 特定の条件で、天気予報画面に雨の画像が表示されること
    - [x] 特定の条件で、天気予報画面に最高気温が表示されること
    - [x] 特定の条件で、天気予報画面に最低気温が表示されること
    - [x] 特定の条件で、天気予報画面にダイアログが表示され、特定のメッセージが表示されること
- [x] 余裕があれば、他の Widget tests も書く
    - [x] 初回表示時に Placeholder が表示されること

## 動作

変更なし

2024-06-27 09:15 UTC, macneko-ayu commented on pubspec.yaml
> +  flutter_svg_test: ^1.0.1
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)
SVG のテストをしやすくするため導入しました
https://pub.dev/packages/flutter_svg_test

2024-07-01 08:59 UTC, blendthink requested changes
@macneko-ayu 
いくつかコメントさせていただきましたのでご確認お願いします 🙏

2024-07-01 08:59 UTC, blendthink commented on test/weather_screen_test.dart
> +  }
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg)
共通化とわかりやすいコメント、とてもステキです✨

2024-07-01 08:59 UTC, blendthink commented on test/weather_screen_test.dart
> +                  最高気温が 33 ℃、最低気温が 22 ℃ と表示されること''', (tester) async {
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg)
テスト内容がとてもわかりやすく記載されていて、とてもレビューしやすく助かりました💡

2024-07-01 08:59 UTC, blendthink commented on test/weather_screen_test.dart
> +              yumemiWeatherProvider.overrideWithValue(mockYumemiWeather),
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)
先ほどのペア作業のときにもお話しましたが、このセッションではこのままで大丈夫です！ 
Session 11 で `Repository` をモックするように変更するで問題ありません 🙆‍♂️

2024-07-01 08:59 UTC, blendthink commented on test/weather_screen_test.dart
> +      when(mockYumemiWeather.fetchWeather(any)).thenThrow(exception);
![must-badge](https://img.shields.io/badge/review-must-red.svg)
`YumemiWeather` の `fetchWeather` でスローされるものは `YumemiWeatherError` のどれかだと思うので、修正お願いします！

もし `CheckedFromJsonException` が発生することをテストしたい場合は `YumemiWeather` の `fetchWeather` からおかしな値が返却されたときだと思います！

2024-07-01 09:34 UTC, macneko-ayu commented on test/weather_screen_test.dart
> +      when(mockYumemiWeather.fetchWeather(any)).thenThrow(exception);
5812dfc259da0a029036d2dff22d3b843f111f50 で修正しました

2024-07-01 09:35 UTC, macneko-ayu commented
@blendthink 
修正しましたので再レビューお願いします🙏

2024-07-01 09:36 UTC, blendthink approved these changes
ご対応ありがとうございます！
![LGTM](https://image.lgtmoon.dev/253648)

2024-07-02 06:27 UTC, merged